import { Component } from '@angular/core';
import {  signal } from '@angular/core';
import { CommonModule } from '@angular/common';  // Import CommonModule
import { FournisseursService } from '../../../services/fournisseurs.service';
import { Fournisseur } from '../../../models/founisseur.model';

import {
  
  ButtonDirective,
  ModalModule
} from '@coreui/angular-pro';
import {
  ColComponent,
  ProgressComponent,
  ToastComponent,
  ToastBodyComponent,
  ToastHeaderComponent,
  ToastModule
} from '@coreui/angular-pro';
import { FormsModule, NgForm } from '@angular/forms';
import { catchError, tap } from 'rxjs/operators';
import { of } from 'rxjs';

@Component({
  selector: 'app-ajout-fournisseur',
  imports: [ ButtonDirective,ModalModule,
    FormsModule,ToastBodyComponent,ToastHeaderComponent,ToastModule,
    CommonModule,ColComponent,ProgressComponent,ToastComponent],
  templateUrl: './ajout-fournisseur.component.html',
  styleUrl: './ajout-fournisseur.component.scss'
})
export class AjoutFournisseurComponent {


  constructor(private fournisseursService: FournisseursService) {}


  fournisseur: Fournisseur = {
    id: '', // Initially empty, will be auto-generated by backend
    nomF: '',
    numTel: '',
    adresse: '',
    mail:''

  };

  
  onSubmit(form : NgForm): void {
    if (form.invalid) {
      Object.keys(form.controls).forEach((field) => {
        const control = form.controls[field];
        control.markAsTouched({ onlySelf: true });
      });
      return;
    }
    
    console.log('Form data being sent to backend:', this.fournisseur);
    const { id, ...fournisseurData } = this.fournisseur;
  
    this.fournisseursService.addFournisseur(fournisseurData).pipe(
      tap(response => {
        console.log('Fournissuer added successfully:', response);
        this.toggleToast("Fournisseur ajouté avec succés!",'success');
        form.resetForm();

        this.fournisseur = { id: '', nomF: '', numTel: '',adresse: '',mail:'' }; // Reset form
      }),
      catchError(error => {
        console.error('Error adding fournissuer:', error);
        this.toggleToast('Erreur lors de l\'ajout du fournisseur!', 'error');


        return of(null); 
      })
    ).subscribe();
  }
  position = 'top-end';
  visible = signal(false);
  percentage = signal(0);
  toastMessage = signal(''); 
  toastType = signal('success');

  toggleToast(message: string, type: 'success' | 'error') {
    this.toastMessage.set(message);
    this.toastType.set(type);
    this.visible.update((value) => !value);
  }

  onVisibleChange($event: boolean) {
    this.visible.set($event);
    this.percentage.set(this.visible() ? this.percentage() : 0);
  }

  onTimerChange($event: number) {
    this.percentage.set($event * 25);
  }
}
