// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250310204151_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChambrePatient", b =>
                {
                    b.Property<Guid>("ChambresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChambresId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("ChambrePatient");
                });

            modelBuilder.Entity("FactureMedicament", b =>
                {
                    b.Property<Guid>("FacturesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicamentsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FacturesId", "MedicamentsId");

                    b.HasIndex("MedicamentsId");

                    b.ToTable("FactureMedicament");
                });

            modelBuilder.Entity("HMS.Models.Chambre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nb_lit")
                        .HasColumnType("int");

                    b.Property<string>("statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chambres");
                });

            modelBuilder.Entity("HMS.Models.DossierM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("liste_analyse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("liste_pres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Dossiers");
                });

            modelBuilder.Entity("HMS.Models.Facture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Prix_admission")
                        .HasColumnType("float");

                    b.Property<double>("Prix_materiel")
                        .HasColumnType("float");

                    b.Property<double>("Prix_medecin")
                        .HasColumnType("float");

                    b.Property<double>("Prix_medicament")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("HMS.Models.Medicament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Compagnie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_Exp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nbr_stock")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medicaments");
                });

            modelBuilder.Entity("HMS.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Grp_Sang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HMS.Models.Personnel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date_Emb")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Date_Naiss")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salaire")
                        .HasColumnType("float");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telephone")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personnels");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("HMS.Models.RendezVous", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date_RDV")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DossierMId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedecinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierMId");

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("Rdv");
                });

            modelBuilder.Entity("HMS.Models.Visiteur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Visiteurs");
                });

            modelBuilder.Entity("HMS.Models.Medecin", b =>
                {
                    b.HasBaseType("HMS.Models.Personnel");

                    b.Property<string>("Grad_med")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Medecins", (string)null);
                });

            modelBuilder.Entity("HMS.Models.PersonnelAdministrative", b =>
                {
                    b.HasBaseType("HMS.Models.Personnel");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("HMS.Models.Pharmacien", b =>
                {
                    b.HasBaseType("HMS.Models.Personnel");

                    b.ToTable("Pharmaciens", (string)null);
                });

            modelBuilder.Entity("ChambrePatient", b =>
                {
                    b.HasOne("HMS.Models.Chambre", null)
                        .WithMany()
                        .HasForeignKey("ChambresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HMS.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FactureMedicament", b =>
                {
                    b.HasOne("HMS.Models.Facture", null)
                        .WithMany()
                        .HasForeignKey("FacturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HMS.Models.Medicament", null)
                        .WithMany()
                        .HasForeignKey("MedicamentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HMS.Models.DossierM", b =>
                {
                    b.HasOne("HMS.Models.Patient", "Patient")
                        .WithOne("DossierMedical")
                        .HasForeignKey("HMS.Models.DossierM", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HMS.Models.Facture", b =>
                {
                    b.HasOne("HMS.Models.Patient", "Patient")
                        .WithOne("Facture")
                        .HasForeignKey("HMS.Models.Facture", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HMS.Models.RendezVous", b =>
                {
                    b.HasOne("HMS.Models.DossierM", null)
                        .WithMany("liste_rdv")
                        .HasForeignKey("DossierMId");

                    b.HasOne("HMS.Models.Medecin", "Medecin")
                        .WithMany("RendezVous")
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HMS.Models.Patient", "Patient")
                        .WithMany("RendezVous")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medecin");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HMS.Models.Medecin", b =>
                {
                    b.HasOne("HMS.Models.Personnel", null)
                        .WithOne()
                        .HasForeignKey("HMS.Models.Medecin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HMS.Models.PersonnelAdministrative", b =>
                {
                    b.HasOne("HMS.Models.Personnel", null)
                        .WithOne()
                        .HasForeignKey("HMS.Models.PersonnelAdministrative", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HMS.Models.Pharmacien", b =>
                {
                    b.HasOne("HMS.Models.Personnel", null)
                        .WithOne()
                        .HasForeignKey("HMS.Models.Pharmacien", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HMS.Models.DossierM", b =>
                {
                    b.Navigation("liste_rdv");
                });

            modelBuilder.Entity("HMS.Models.Patient", b =>
                {
                    b.Navigation("DossierMedical")
                        .IsRequired();

                    b.Navigation("Facture")
                        .IsRequired();

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("HMS.Models.Medecin", b =>
                {
                    b.Navigation("RendezVous");
                });
#pragma warning restore 612, 618
        }
    }
}
