import { Component, signal } from '@angular/core';
import { MedicamentService } from '../../services/medicament.service';
import { Medicament } from '../../models/medicaments.model';
import { CommonModule } from '@angular/common';  // Import CommonModule

import {
  BadgeComponent,
  ButtonDirective,
  CollapseDirective,
  IColumn,
  SmartTableComponent,
  TemplateIdDirective,
  ModalModule
} from '@coreui/angular-pro';
import {
  ButtonCloseDirective,
  ModalBodyComponent,
  ColComponent,
  ModalComponent,
  ModalFooterComponent,
  ModalHeaderComponent,
  ModalTitleDirective,
  ThemeDirective,
  ProgressComponent,
  ToastComponent,
  ToastBodyComponent,
  ToastHeaderComponent,
  ToastModule
} from '@coreui/angular-pro';
import { FormsModule } from '@angular/forms';
import { catchError, tap } from 'rxjs/operators';
import { of } from 'rxjs';
import { AlertComponent } from '@coreui/angular-pro';  // Import alert components


@Component({
  selector: 'app-ajout-med',
  imports: [BadgeComponent, ButtonDirective, CollapseDirective, SmartTableComponent, TemplateIdDirective, ModalModule,
      ButtonCloseDirective,
      ModalBodyComponent,
      ModalComponent,
      ModalFooterComponent,
      ModalHeaderComponent,
      ModalTitleDirective,
      ThemeDirective,
      FormsModule, AlertComponent,ToastBodyComponent,ToastHeaderComponent,ToastModule,
      CommonModule,ColComponent,ProgressComponent,ToastComponent],
  templateUrl: './ajout-med.component.html',
  styleUrl: './ajout-med.component.scss'
})
export class AjoutMedComponent {

  constructor(private medicamentService: MedicamentService) {}


  medicament: Medicament = {
    id: '', // Initially empty, will be auto-generated by backend
    nom: '',
    description: '',
    nbr_stock: 0,
    compagnie: '',
    date_Exp: new Date() // Initial date
  };

  /*// Alert state
  visible_alert: boolean = false;
  alertMessage: string = '';
  alertType: string = 'success';  // success, danger, info, etc.
  medicamentsData: Medicament[] = [];
*/
  columns: IColumn[] = [
    { key: 'nom', label: 'Nom' },
    { key: 'nbr_stock', label: 'Quantité de Stock' },
    { key: 'compagnie', label: 'Fournisseur' },
    { key: 'date_Exp', label: 'Date d\'Expiration ' },
    { key: 'show', label: '', _style: { width: '5%' }, filter: false, sorter: false }
  ];

  /*showAlert(message: string, type: string): void {
    console.log('Showing alert:', message, type);  // Add this log to check if the method is triggered
    this.alertMessage = message;
    this.alertType = type;
    this.visible_alert = true;
    setTimeout(() => this.visible_alert = false, 5000);  // Hide the alert after 5 seconds
  }*/

    isInvalidDate(): boolean {
      const today = new Date();
      const expirationDate = new Date(this.medicament.date_Exp);
      return expirationDate <= today;
    }
  
  onSubmit(): void {
    if (this.medicament.nbr_stock < 0) {
      this.toggleToast("Le stock ne peut pas être négatif!", 'error');
      return;
    }
    if (this.isInvalidDate()) {
      this.toggleToast("La date d'expiration doit être après aujourd'hui!", 'error');
      return;
    }
    console.log('Form data being sent to backend:', this.medicament);
    const { id, ...medicamentData } = this.medicament;
  
    this.medicamentService.addMedicament(medicamentData).pipe(
      tap(response => {
        console.log('Medicament added successfully:', response);
        this.toggleToast("Médicament ajouté avec succés!",'success');

        this.medicament = { id: '', nom: '', description: '', nbr_stock: 0, compagnie: '', date_Exp: new Date() }; // Reset form
      }),
      catchError(error => {
        console.error('Error adding medicament:', error);
        this.toggleToast('Erreur lors de l\'ajout du médicament!', 'error');


        return of(null); 
      })
    ).subscribe();
  }
  position = 'top-end';
  visible = signal(false);
  percentage = signal(0);
  toastMessage = signal(''); 
  toastType = signal('success');

  toggleToast(message: string, type: 'success' | 'error') {
    this.toastMessage.set(message);
    this.toastType.set(type);
    this.visible.update((value) => !value);
  }

  onVisibleChange($event: boolean) {
    this.visible.set($event);
    this.percentage.set(this.visible() ? this.percentage() : 0);
  }

  onTimerChange($event: number) {
    this.percentage.set($event * 25);
  }
}
