import { Component, OnInit, signal } from '@angular/core';
import { MedicamentService } from '../../services/medicament.service';
import { Medicament } from '../../models/medicaments.model';
import { Fournisseur } from '../../models/founisseur.model';

import { CommonModule } from '@angular/common';  // Import CommonModule

import {
  
  ButtonDirective,
  CollapseDirective,
  IColumn,
  SmartTableComponent,
  TemplateIdDirective,
  ModalModule
} from '@coreui/angular-pro';
import {
  ProgressComponent,
  ToastComponent,
  ToastBodyComponent,
  ToastHeaderComponent,
  ToastModule
} from '@coreui/angular-pro';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-medicaments',
  standalone: true,
  imports: [
ButtonDirective, CollapseDirective, SmartTableComponent, TemplateIdDirective, ModalModule,
    FormsModule,
    CommonModule,
    ProgressComponent,
    ToastComponent,
    ToastBodyComponent,
    ToastHeaderComponent,
    ToastModule
  ],
  templateUrl: './medicaments.component.html',
})
export class MedicamentsComponent implements OnInit {

  medicament: Medicament = {
    id: '', // Initially empty, will be auto-generated by backend
    nom: '',
    description: '',
    nbr_stock: 0,
    fournisseurId: '' ,
    CategorieId:'',
    date_Exp: new Date() // Initial date
  };


  medicamentsData: Medicament[] = [];


  details_visible: { [key: string]: boolean } = {};

  columns: IColumn[] = [
    { key: 'nom', label: 'Nom' },
    { key: 'nbr_stock', label: 'Quantité de Stock' },
    { key: 'fournisseur', label: 'Fournisseur' },
    { key: 'categorie', label: 'Categorie' },
    { key: 'date_Exp', label: 'Date d\'Expiration ' },
    { key: 'show', label: '', _style: { width: '5%' }, filter: false, sorter: false },
    { key: 'delete', label: '', _style: { width: '5%' }, filter: false, sorter: false }

  ];

  constructor(private medicamentService: MedicamentService) {}

  ngOnInit(): void {
    this.medicamentService.getMedicaments().subscribe({
      next: (data) => (this.medicamentsData = data),
      error: (err) => console.error('Error fetching medicaments:', err)
    });
  }

  toggleDetails(id: string) {
    this.details_visible[id] = !this.details_visible[id];
  }

// Properties for modal control
visible_modal: boolean = false;
selectedId: string | null = null;

// Open modal with the selected medicament ID
openDeleteModal(id: string) {
  this.selectedId = id;
  this.visible_modal = true;
}

// Close modal and reset selected ID
closeModal() {
  this.visible_modal = false;
  this.selectedId = null;
}

// Confirm deletion
confirmDelete() {
  if (this.selectedId) {
    this.medicamentService.deleteMedicament(this.selectedId).subscribe({
      next: () => {
        console.log(`Medicament with id ${this.selectedId} deleted.`);
        this.toggleToast('Médicament supprimé avec succès!', 'success');

        // Remove deleted medicament from the list
        this.medicamentsData = this.medicamentsData.filter(m => m.id !== this.selectedId);

        this.closeModal(); // Close modal after deletion
      },
      error: (err) => {
        console.error('Error deleting medicament:', err);
        this.toggleToast('Erreur lors de la suppression du médicament!', 'error');
      }
    });
  }
}

  

  updateStock(medicament: Medicament, newStock: any): void {
    console.log("Updating stock for:", medicament, "New stock:", newStock);
  
    const stockValue = Number(newStock);
    if (isNaN(stockValue) || stockValue < 0) {
      this.toggleToast('Stock ne peut pas être negatif!', 'error');

      return;
    }
  
    if (!medicament.id) {
      console.error('Medicament ID is undefined');
      return;
    }
  
    // ✅ Ensure the property name matches the backend
    const updatedMedicament = { 
      ...medicament, 
    };
  
    this.medicamentService.updateMedicament(medicament.id, updatedMedicament).subscribe({
      next: () => {
        medicament.nbr_stock = stockValue; // Update UI
        console.log(`Stock updated successfully: ${medicament.nbr_stock}`);
        this.toggleToast('Stock modifié avec succés!', 'success');


      },
      error: (err) => console.error('Error updating stock:', err)
    });
  }
  
  position = 'top-end';
    visible = signal(false);
    percentage = signal(0);
    toastMessage = signal(''); 
    toastType = signal('success');
  
    toggleToast(message: string, type: 'success' | 'error') {
      this.toastMessage.set(message);
      this.toastType.set(type);
      this.visible.update((value) => !value);
    }
  
    onVisibleChange($event: boolean) {
      this.visible.set($event);
      this.percentage.set(this.visible() ? this.percentage() : 0);
    }
  
    onTimerChange($event: number) {
      this.percentage.set($event * 25);
    }
    toggleLiveDemo() {
      this.visible_modal = !this.visible_modal;
    }
  
    handleLiveDemoChange(event: any) {
      this.visible_modal = event;
    }
  
  
}
