import { Component } from '@angular/core';
import {  OnInit } from '@angular/core';
import { CategorieService } from '../../services/categorie.service';
import { CategorieMedicament } from '../../models/categorie.model';
import { CommonModule } from '@angular/common';
import {
  
  ButtonDirective,
  IColumn,
  CollapseDirective,
  TemplateIdDirective,
  ModalModule
} from '@coreui/angular-pro';
import {
  ProgressComponent,
  ToastComponent,
  ToastBodyComponent,
  ToastHeaderComponent,
  ToastModule
} from '@coreui/angular-pro';
import { FormsModule, NgForm } from '@angular/forms';
import { RouterModule } from '@angular/router';  // Import RouterModule
import {  signal } from '@angular/core';


import {
  BadgeComponent,

  SmartTableComponent,

} from '@coreui/angular-pro';
import {
  ButtonCloseDirective,
  ModalBodyComponent,
  ColComponent,
  ModalComponent,
  ModalFooterComponent,
  ModalHeaderComponent,
  ModalTitleDirective,
  ThemeDirective,
} from '@coreui/angular-pro';
import { catchError, tap } from 'rxjs/operators';
import { of } from 'rxjs';
import { AlertComponent } from '@coreui/angular-pro';  // Import alert components


@Component({
  selector: 'app-categorie',
  imports: [CommonModule, CollapseDirective, TemplateIdDirective, ModalModule,
    FormsModule,
    CommonModule,
    ProgressComponent,
    ToastComponent,
    ToastBodyComponent,
    ToastHeaderComponent,
    ToastModule,RouterModule,
  BadgeComponent, ButtonDirective, CollapseDirective, TemplateIdDirective, ModalModule,
      ButtonCloseDirective,
      ModalBodyComponent,
      ModalComponent,
      ModalFooterComponent,
      ModalHeaderComponent,
      ModalTitleDirective,
      ThemeDirective,
      FormsModule, AlertComponent,ToastBodyComponent,ToastHeaderComponent,ToastModule,
      CommonModule,ColComponent,ProgressComponent,ToastComponent],
  templateUrl: './categorie.component.html',
  styleUrl: './categorie.component.scss'
})
export class CategorieComponent implements OnInit{

  categories: CategorieMedicament[] = [];
  constructor(private categorieService: CategorieService) {}

  
  ngOnInit(): void {
    this.categorieService.getCategories().subscribe({
      next: (data) => {
        this.categories = data
        console.log(this.categories)
      },
      error: (err) => console.error('Error fetching categories:', err)
    });
  }
  deleteCategorie(categorie: CategorieMedicament): void {
    if (!categorie?.id) {  // Use optional chaining
      console.error('Error: Fournisseur ID is undefined', categorie);
      return;
    }
  
    if (confirm(`Confirmer la suppression de ${categorie.name} ?`)) {
      this.categorieService.deleteCategorie(categorie.id).subscribe({
        next: () => {
          this.categories = this.categories.filter(f => f.id !== categorie.id);
        },
        error: (err) => console.error('Error deleting fournisseur:', err)
      });
    }
  }

  categ: CategorieMedicament = {
      id: '', // Initially empty, will be auto-generated by backend
      name: '',
    };

    
    onSubmit(form : NgForm): void {
      if (form.invalid) {
        Object.keys(form.controls).forEach((field) => {
          const control = form.controls[field];
          control.markAsTouched({ onlySelf: true });
        });
        return;
      }
      
      console.log('Form data being sent to backend:', this.categ);
      const { id, ...CategorieData } = this.categ;
    
      this.categorieService.addCategorie(CategorieData).pipe(
        tap(response => {
          console.log('Catégorie added successfully:', response);
          this.toggleToast("Catégorie ajouté avec succés!",'success');
          form.resetForm();
  
          this.categ = { id: '', name: ''}; // Reset form
        }),
        catchError(error => {
          console.error('Error adding Catégorie:', error);
          this.toggleToast('Erreur lors de l\'ajout de la catégorie!', 'error');
  
  
          return of(null); 
        })
      ).subscribe();
    }
    position = 'top-end';
  visible = signal(false);
  percentage = signal(0);
  toastMessage = signal(''); 
  toastType = signal('success');

  toggleToast(message: string, type: 'success' | 'error') {
    this.toastMessage.set(message);
    this.toastType.set(type);
    this.visible.update((value) => !value);
  }

  onVisibleChange($event: boolean) {
    this.visible.set($event);
    this.percentage.set(this.visible() ? this.percentage() : 0);
  }

  onTimerChange($event: number) {
    this.percentage.set($event * 25);
  }

}